# Ejercicio peatones en la pandemia

Para realizar este ejercicio vamos a utilizar el fichero .csv de la página del Portal de Datos Abiertos del Ayuntamiento de Madrid (https://datos.madrid.es/). Desde dicha página buscamos `peatones`y nos lleva a `Aforos de peatones y bicicletas` (https://datos.madrid.es/dataset/300321-0-aforos-peatones-bicicletas). Aquí tenemos que descargarnos el fichero csv de peatones correspondiente al año 2020
https://datos.madrid.es/dataset/300321-0-aforos-peatones-bicicletas/downloads.
 
 La descripción de cada campo del fichero es:

| Número de columna | Nombre columna            | Descripción                                                   | Valores esperados              |
|-------------------|---------------------------|---------------------------------------------------------------|--------------------------------|
| 1                 | fecha                     | Fecha del registro. Formato de fecha: DD-MM-AAAA.            |                                |
| 2                 | hora                      | Hora del registro. Formato de hora: HH:MM.                   |                                |
| 3                 | identificador             | Identificador único del registro.                             | Texto                          |
| 4                 | peatones                  | Número de bicicletas registradas.                             | Numérico                       |
| 5                 | device_id                 | Identificador único del registro.                             | Texto                          |
| 6                 | Número_distrito           | Número identificativo del distrito.                           | Numérico                       |
| 7                 | distrito                  | Nombre del distrito.                                          | Texto                          |
| 8                 | direccion                 | Dirección exacta del aforo.                                   | Texto                          |
| 9                 | observaciones_direccion   | Observaciones adicionales sobre la dirección del tráfico.     | Texto                          |
| 10                | latitude                  | Latitud geográfica del registro.                              | Número decimal (40.400000)     |
| 11                | longitude                 | Longitud geográfica del registro.                             | Número decimal (3.700000)      |

## Carga de datos y exploración del dataframe

Después de descargarnos el fichero `300321-3-aforos-peatones-bicicletas-csv.csv` correspondiente al año 2020  de la web https://datos.madrid.es/dataset/300321-0-aforos-peatones-bicicletas/downloads, lo dejamos en nuestra carpeta llamada Data y lo importamos como un dataframe llamado df.

Lo primero que tenemos que hacer es ver el contenido del fichero con una aplicación de texto plano y veo que el csv no está separado por `comas`, sino por `punto y coma` y además, utiliza la `coma` como separador decimal en LATITUD y LONGITUD. Así que se debe indicar `sep=";"` y ` decimal=","` como parámetros de la carga de pandas `pd.read_csv`.

In [176]:
import pandas as pd

df = pd.read_csv(
    "./Data/300321-3-aforos-peatones-bicicletas-csv.csv",
    sep=";",
    decimal=","
)

Muestra el DataFrame para comprobar que la carga se ha realizado correctamente. Puedes escribir simplemente el nombre del objeto.

In [178]:
df

,FECHA,HORA,IDENTIFICADOR,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD
0,01/01/2020 0:00,0:00,PERM_PEA02_PM01,1269,1,Centro,Calle Fuencarral,22,28004,Calle peatonal,40.422009,-3.700892
1,01/01/2020 1:00,1:00,PERM_PEA02_PM01,1137,1,Centro,Calle Fuencarral,22,28004,Calle peatonal,40.422009,-3.700892
2,01/01/2020 2:00,2:00,PERM_PEA02_PM01,843,1,Centro,Calle Fuencarral,22,28004,Calle peatonal,40.422009,-3.700892
3,01/01/2020 3:00,3:00,PERM_PEA02_PM01,711,1,Centro,Calle Fuencarral,22,28004,Calle peatonal,40.422009,-3.700892
4,01/01/2020 4:00,4:00,PERM_PEA02_PM01,476,1,Centro,Calle Fuencarral,22,28004,Calle peatonal,40.422009,-3.700892
...,...,...,...,...,...,...,...,...,...,...,...,...
166891,31/12/2020 23:00,23:00,PERM_PEA15_PM01,173,1,Centro,Calle Fuencarral,22,28004,Calle peatonal,40.422009,-3.700892
166892,31/12/2020 23:00,23:00,PERM_PEA16_PM01,105,2,Arganzuela,Plaza del Emperador Carlos V,11,28012,Acera Impares,40.411109,-3.696471
166893,31/12/2020 23:00,23:00,PERM_PEA17_PM01,113,2,Arganzuela,Plaza del Emperador Carlos V,11,28012,Acera Impares,40.411109,-3.696471
166894,31/12/2020 23:00,23:00,PERM_PEA18_PM01,76,1,Centro,Calle Fuencarral,22,28004,Calle peatonal,40.422009,-3.700892
166895,31/12/2020 23:00,23:00,PERM_PEA19_PM01,6,1,Centro,Calle Fuencarral,22,28004,Calle peatonal,40.422009,-3.700892

## Analizar y transformar los tipos de datos


Lo primero es conocer qué tipo de datos tiene cada columna. Lo puedes hacer con `info()` que es especialmente útil porque nos muestra el número de valores *no nulos*.

Observa que `LATITUD` y `LONGITUD` quedan como `float64`.

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166896 entries, 0 to 166895
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   FECHA                    166896 non-null  object
 1   HORA                     166896 non-null  object
 2   IDENTIFICADOR            166896 non-null  object
 3   PEATONES                 166896 non-null  int64
 4   NÚMERO_DISTRITO          166896 non-null  int64
 5   DISTRITO                 166896 non-null  object
 6   NOMBRE_VIAL              166896 non-null  object
 7   NÚMERO                   166896 non-null  int64
 8   CÓDIGO_POSTAL            166896 non-null  int64
 9   OBSERVACIONES_DIRECCION  166896 non-null  object
 10  LATITUD                  166896 non-null  float64
 11  LONGITUD                 166896 non-null  float64
dtypes: float64(2), int64(4), object(6)
memory usage: 15.3+ MB

`object` no dice exactamente qué clase de objeto hay dentro de la columna. En pandas, significa que la columna contiene valores almacenados como objetos de Python, muy frecuentemente cadenas de texto (str).
Puedes comprobar el tipo de los elementos accediendo, por ejemplo, al primer elemento de FECHA con `iloc[0]` y sobre esta celda utilizar `type()`.

In [183]:
type(df["FECHA"].iloc[0])

str

Pero en python tenemos un tipo de datos específico para la fecha y la hora

### Fechas 
En Python podemos trabajar con distintos tipos de datos temporales:
- `date`: representa una fecha: año, mes y día.
- `time`: representa una hora: hora, minutos, segundos.
- `datetime`: representa fecha y hora conjuntamente

Como hemos visto, pandas todavía no reconoce `FECHA` como una fecha, sino que la ha leído como texto. Por lo tanto usamos `pd.to_datetime()` para convertir los tipos de los valores. Además, necesitamos el parámetro `dayfirst = True` para indicar a pandas que, al interpretar una fecha, el primer número corresponde al día pues la fecha está escrita con el día antes del mes.

Ejecuto `df["FECHA"] = pd.to_datetime(df["FECHA"], dayfirst=True)` pero me da error.

In [186]:
# df["FECHA"] = pd.to_datetime(df["FECHA"], dayfirst=True)

Y me da error, pero... ¿qué ha pasado?

Pues que en el fichero hay dos formatos diferentes en las fechas, unos es con la hora `01/01/2020 00:00` y el otro es sin hora `02/09/2020`.
Pandas ha inferido inicialmente el formato %d/%m/%Y %H:%M pero ha detectado un valor que no seguía este formato.
Si miramos al final del error, 

>ValueError: time data "02/09/2020" doesn't match format "%d/%m/%Y %H:%M", at position 5880)

nos dice que en la posición 5880 se ha encontrado 02/09/2020 sin hora 
y nos aconseja hacer varias cosas, la más interesante es la que dice: 

>`format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

Vuelve a realizar la conversión de FECHA, pero esta vez teniendo en cuenta el mensaje de error.

In [189]:
df["FECHA"] = pd.to_datetime(
    df["FECHA"],
    dayfirst = True,
    format = "mixed"
)

Volvemos a comprobar el tipo del primer valor de la columna `FECHA`.

In [191]:
print(df["FECHA"].dtype)    
# Sin print sale <M8[ns] que es una representación interna de NumPy y significa:
# - M → datetime
# - 8 → ocupa 8 bytes
# - ns → nanosegundos como unidad de precisión

print(type(df["FECHA"].iloc[0]))    # Timestamp es el tipo que utiliza pandas para representar una fecha y hora.

# FECHA
#   │
#   ├── dtype de la columna → datetime64[ns]
#   │
#   └── cada elemento → pandas.Timestamp

datetime64[ns]
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

Ahora sí que estamos trabajando con fechas reales y podemos, por ejemplo, 
extrae de FECHA una parte concreta utilizando el accesor `.dt`. Prueba primero con el año (`df["FECHA"].dt.year`), después con el mes y finalmente con el nombre del día de la semana.

In [193]:
print('La parte año de la fecha es:')
df["FECHA"].dt.year

La parte año de la fecha es:

0         2020
1         2020
2         2020
3         2020
4         2020
          ...
166891    2020
166892    2020
166893    2020
166894    2020
166895    2020
Name: FECHA, Length: 166896, dtype: int32

In [194]:
print('La parte mes de la fecha es:')
df["FECHA"].dt.month

La parte mes de la fecha es:

0          1
1          1
2          1
3          1
4          1
          ..
166891    12
166892    12
166893    12
166894    12
166895    12
Name: FECHA, Length: 166896, dtype: int32

In [195]:
print('La parte día de la fecha es:')
df["FECHA"].dt.day_name()

La parte día de la fecha es:

0         Wednesday
1         Wednesday
2         Wednesday
3         Wednesday
4         Wednesday
            ...
166891     Thursday
166892     Thursday
166893     Thursday
166894     Thursday
166895     Thursday
Name: FECHA, Length: 166896, dtype: object

También podemos comparar dos fechas, para ello vamos a obtener una fecha de la primera fila y otra de la última. Acuérdate que `iloc[0]` devuelve una fila completa, así que tendrás que seleccionar además la columna `FECHA`. Imprime las dos fechas y después puedes restalas.

In [197]:
fecha1 = df.iloc[0]["FECHA"]
fecha2 = df.iloc[len(df) - 1]["FECHA"]

print(fecha1)
print(fecha2)

print(fecha2 - fecha1)

2020-01-01 00:00:00
2020-12-31 23:00:00
365 days 23:00:00

### Horas

Ahora vamos con la columna `HORA` que aparece como textode la forma `00:00`y `01:00`. Estos valores
podemos convertirlos a un tipo de hora de pandas pero, pandas no tiene una función `pd.to_time()`. Necesitamos hacer un `pd.to_datetime()` con formato de fecha `%H:%M`como parámetro. Finalmente, aplicamos `pd.to_datetime().dt.time` para quedarnos únicamente con la parte de la hora.

```python
df["HORA"] = pd.to_datetime(
    df["HORA"],
    format="%H:%M"
).dt.time
```

In [199]:
df["HORA"] = pd.to_datetime(
    df["HORA"],
    format="%H:%M"
).dt.time

In [200]:
# Ojo que el print(df["HORA"].dtype)  dice que es un object

# ¿Por qué ocurre?
# Porque datetime.time es un objeto de Python, no un tipo de datos nativo de NumPy que pandas pueda almacenar como un dtype temporal especializado.

# pandas no tiene un dtype específico para una columna de objetos datetime.time, por lo que la columna aparece como object. 

# Una columna de pandas puede tener dtype="object" aunque sus elementos sean objetos de Python de un tipo concreto. Por ejemplo, una columna cuyos elementos son datetime.time tendrá normalmente dtype=object
# Y no hay ningún error

# Columna HORA
#      │
#      ├── dtype de pandas → object
#      │
#      └── cada elemento → datetime.time
# 
# Esto es diferente de FECHA. Podemos verlo claramente.
# 
# print("FECHA:")
# print(df["FECHA"].dtype)
# print(type(df["FECHA"].iloc[0]))

# print("HORA:")
# print(df["HORA"].dtype)
# print(type(df["HORA"].iloc[0]))
# 
# FECHA:
# datetime64[ns]
# <class 'pandas._libs.tslibs.timestamps.Timestamp'>

# HORA:
# object
# <class 'datetime.time'>
# 
# Entonces, ¿está bien convertir HORA a datetime.time? 
# 
# 


print(df["HORA"].dtype) 
print(type(df["HORA"].iloc[0]))

object
<class 'datetime.time'>

## Seleccionar ciertas columnas de la tabla, las que me interesan


Crea un nuevo DataFrame `df_1` seleccionando únicamente las columnas:
`FECHA`, `HORA`, `PEATONES`, `DISTRITO`, `NOMBRE_VIAL` y `NÚMERO`.
Para seleccionar varias columnas necesitas una lista de nombres dentro de los corchetes.
Usa `.copy()` para crear un nuevo DataFrame independiente.

In [202]:
df_1 = df[["FECHA", "HORA", "PEATONES", "DISTRITO", "NOMBRE_VIAL", "NÚMERO"]].copy()

## Cambiar el nombre de la columna `NOMBRE_VIAL`por `DIRECCION`. 

Utiliza `rename()` para cambiar el nombre de `NOMBRE_VIAL` por `DIRECCION`.
Después puedes consultar `df_1.columns` para comprobar el cambio.

In [204]:
df_1 = df_1.rename(columns={"NOMBRE_VIAL": "DIRECCION"})
df_1.columns

Index(['FECHA', 'HORA', 'PEATONES', 'DISTRITO', 'DIRECCION', 'NÚMERO'], dtype='object')

## Calcular el total de peatones por día de la semana

Para analizar los peatones por día de la semana, necesitamos añadir una columna una nueva columna con dicho dato.
Es decir, a partir de `FECHA`, crea una nueva columna llamada `DIA_SEMANA`.
El accesor `.dt` tiene un método `day_name()` que devuelve el nombre del día de la semana.

In [206]:
df_1["DIA_SEMANA"] = df_1["FECHA"].dt.day_name()
df_1

,FECHA,HORA,PEATONES,DISTRITO,DIRECCION,NÚMERO,DIA_SEMANA
0,2020-01-01 00:00:00,00:00:00,1269,Centro,Calle Fuencarral,22,Wednesday
1,2020-01-01 01:00:00,01:00:00,1137,Centro,Calle Fuencarral,22,Wednesday
2,2020-01-01 02:00:00,02:00:00,843,Centro,Calle Fuencarral,22,Wednesday
3,2020-01-01 03:00:00,03:00:00,711,Centro,Calle Fuencarral,22,Wednesday
4,2020-01-01 04:00:00,04:00:00,476,Centro,Calle Fuencarral,22,Wednesday
...,...,...,...,...,...,...,...
166891,2020-12-31 23:00:00,23:00:00,173,Centro,Calle Fuencarral,22,Thursday
166892,2020-12-31 23:00:00,23:00:00,105,Arganzuela,Plaza del Emperador Carlos V,11,Thursday
166893,2020-12-31 23:00:00,23:00:00,113,Arganzuela,Plaza del Emperador Carlos V,11,Thursday
166894,2020-12-31 23:00:00,23:00:00,76,Centro,Calle Fuencarral,22,Thursday
166895,2020-12-31 23:00:00,23:00:00,6,Centro,Calle Fuencarral,22,Thursday

Si queremos los nombres en español debemos usar `day_name()` devuelve los nombres de los días en inglés. A parte, crea un diccionario que relacione cada nombre en inglés con su equivalente en español y utiliza un bucle para realizar la sustitución.

In [208]:
dias = {
    "Monday": "Lunes",
    "Tuesday": "Martes",
    "Wednesday": "Miércoles",
    "Thursday": "Jueves",
    "Friday": "Viernes",
    "Saturday": "Sábado",
    "Sunday": "Domingo"
}

df_1["DIA_SEMANA"] = df_1["FECHA"].dt.day_name()

for i in range(len(df_1)):
    df_1.loc[i, "DIA_SEMANA"] = dias[df_1.loc[i, "DIA_SEMANA"]]

# Esto tarda

df_1

,FECHA,HORA,PEATONES,DISTRITO,DIRECCION,NÚMERO,DIA_SEMANA
0,2020-01-01 00:00:00,00:00:00,1269,Centro,Calle Fuencarral,22,Miércoles
1,2020-01-01 01:00:00,01:00:00,1137,Centro,Calle Fuencarral,22,Miércoles
2,2020-01-01 02:00:00,02:00:00,843,Centro,Calle Fuencarral,22,Miércoles
3,2020-01-01 03:00:00,03:00:00,711,Centro,Calle Fuencarral,22,Miércoles
4,2020-01-01 04:00:00,04:00:00,476,Centro,Calle Fuencarral,22,Miércoles
...,...,...,...,...,...,...,...
166891,2020-12-31 23:00:00,23:00:00,173,Centro,Calle Fuencarral,22,Jueves
166892,2020-12-31 23:00:00,23:00:00,105,Arganzuela,Plaza del Emperador Carlos V,11,Jueves
166893,2020-12-31 23:00:00,23:00:00,113,Arganzuela,Plaza del Emperador Carlos V,11,Jueves
166894,2020-12-31 23:00:00,23:00:00,76,Centro,Calle Fuencarral,22,Jueves
166895,2020-12-31 23:00:00,23:00:00,6,Centro,Calle Fuencarral,22,Jueves

In [209]:
peatones_dia = df_1.groupby("DIA_SEMANA")["PEATONES"].sum()

print(peatones_dia)

DIA_SEMANA
Domingo      6882035
Jueves       6112174
Lunes        5944647
Martes       5914144
Miércoles    6121263
Sábado       8363292
Viernes      6806128
Name: PEATONES, dtype: int64

## Crear un DataFrame con el distrito Centro

Antes de filtrar por el distrito `Centro`, conviene conocer qué valores aparecen en la columna `DISTRITO`. Utiliza el método `unique()` que devuelve los distintos valores de una columna.

In [212]:
print(df_1["DISTRITO"].unique())

['Centro' 'Chamberí' 'Latina' 'Moncloa-Aravaca' 'Arganzuela']

Ahora, crea el dataFrame `df_Centro` con todas las observaciones que contienen el distrito Centro.

In [214]:
df_Centro = df_1[df_1["DISTRITO"] == "Centro"].copy()

## Peatones de Madrid a las 23:00

Seleccionar las observaciones de `df_1` de las 23:00. 
Para ello filtra `df_1` utilizando la columna `HORA`.
Como `HORA` contiene objetos `datetime.time`, puedes comparar con una hora creada a partir de `"23:00"` o con `datetime.time(23, 0)`, es lo mismo.
Hago las dos versiones creando dos nuevos dataframes: `df_Madrid_23h_v1` y `df_Madrid_23h_v2`. El primero usa `"23:00"` y el segundo `datetime.time(23, 0)`. Después compruebo sus dimensiones y pregunto si son iguales con `df1.equals(df2)`.

In [216]:
df_Madrid_23h_v1 = df_1[df_1["HORA"] == pd.to_datetime("23:00", format="%H:%M").time()].copy()

import datetime
df_Madrid_23h_v2 = df_1[df_1["HORA"] == datetime.time(23, 0)].copy()

print(df_Madrid_23h_v1.shape)
print(df_Madrid_23h_v2.shape)
print(df_Madrid_23h_v1.equals(df_Madrid_23h_v2))

(6954, 7)
(6954, 7)
True

## Peatones de Centro a las 23:00

Seleccionar las observaciones de `df_Centro` de las 23:00. 

Observación: Necesitarás combinar las condiciones de distrito y hora si partes de `df_1`, pero aquí ya tenemos filtrado el distrito. Por esto, es importante partir de `df_Centro` y añadir la condición de que la hora sea `23:00`.

Después, observamos las filas y columnas de la tabla.

In [218]:
df_Centro_23 = df_Centro[df_Centro["HORA"] == pd.to_datetime("23:00", format="%H:%M").time()].copy()
df_Centro_23.shape

(4758, 7)

## Total de peatones de Madrid por mes

Para estudiar los totales por mes, primero creamos una nueva columna `MES` extrayendo el número de mes de `FECHA` mediante `.dt` porque fechas lleva mes y hora.

In [220]:
df_1["MES"] = df_1["FECHA"].dt.month
df_1

,FECHA,HORA,PEATONES,DISTRITO,DIRECCION,NÚMERO,DIA_SEMANA,MES
0,2020-01-01 00:00:00,00:00:00,1269,Centro,Calle Fuencarral,22,Miércoles,1
1,2020-01-01 01:00:00,01:00:00,1137,Centro,Calle Fuencarral,22,Miércoles,1
2,2020-01-01 02:00:00,02:00:00,843,Centro,Calle Fuencarral,22,Miércoles,1
3,2020-01-01 03:00:00,03:00:00,711,Centro,Calle Fuencarral,22,Miércoles,1
4,2020-01-01 04:00:00,04:00:00,476,Centro,Calle Fuencarral,22,Miércoles,1
...,...,...,...,...,...,...,...,...
166891,2020-12-31 23:00:00,23:00:00,173,Centro,Calle Fuencarral,22,Jueves,12
166892,2020-12-31 23:00:00,23:00:00,105,Arganzuela,Plaza del Emperador Carlos V,11,Jueves,12
166893,2020-12-31 23:00:00,23:00:00,113,Arganzuela,Plaza del Emperador Carlos V,11,Jueves,12
166894,2020-12-31 23:00:00,23:00:00,76,Centro,Calle Fuencarral,22,Jueves,12
166895,2020-12-31 23:00:00,23:00:00,6,Centro,Calle Fuencarral,22,Jueves,12

Ahora agrupamos y sumamos los peatones, es decir,  agrupamos por `MES` y seleccionamos la columna `PEATONES`.

¿Qué función de agregación necesitamos para obtener el total de peatones de cada mes?

Comprueba el resultado de la agrupación.
Deberías obtener un valor para cada uno de los meses disponibles.

In [222]:

peatones_mes = df_1.groupby("MES")["PEATONES"].sum()

print(peatones_mes)

MES
1     8006983
2     7361212
3     3241413
4      490313
5     1968095
6     3503517
7     3380743
8     3179427
9     3587082
10    3646475
11    3461438
12    4316985
Name: PEATONES, dtype: int64

## Calcular el total de peatones en una fecha concreta y por distrito

Queremos saber cuántos peatones había en la calle, por ejemplo, el 15 de marzo del 2020. Para esto hay que seguir los siguientes pasos:

1. A partir del DataFrame df_1, seleccionar los registros del 15 de marzo de 2020 y dejarlos en un nuevo 'df_fecha`.

2. Calcular el total de peatones aplicando el método `sum()` a la variable `PEATONES`.

3. Calcular el total por distrito

In [224]:
# 1. Seleccionar los registros del 15 de marzo de 2020

fecha = pd.to_datetime("15/03/2020", dayfirst=True)

df_fecha = df_1[df_1["FECHA"].dt.date == fecha.date()].copy()

# 2. Calcular el total de peatones

total_peatones = df_fecha["PEATONES"].sum()

print("Total de peatones:", total_peatones)

# 3. Calcular el total por distrito

peatones_distrito = df_fecha.groupby("DISTRITO")["PEATONES"].sum()

peatones_distrito = peatones_distrito.sort_values(ascending=False)

print(peatones_distrito)

Total de peatones: 76945
DISTRITO
Centro             56432
Chamberí            7329
Arganzuela          6234
Moncloa-Aravaca     3555
Latina              3395
Name: PEATONES, dtype: int64

## Las 10 calles con más peatones

Pasos:

1. A partir del DataFrame df_1, agrupa los registros por calle, utilizando la columna DIRECCION.

2. Calcula el total de peatones registrados en cada calle.

3. Ordena las calles de mayor a menor número de peatones.

4. Muestra las 10 calles con mayor número total de peatones.

In [226]:
# 1. Calcular el total de peatones por calle

peatones_calle = df_1.groupby("DIRECCION")["PEATONES"].sum()

# 2. Ordenar de mayor a menor

peatones_calle = peatones_calle.sort_values(ascending=False)

# 3. Seleccionar las 10 calles con más peatones

top_10 = peatones_calle.head(10)

print(top_10)

DIRECCION
Calle Fuencarral                20192010
Gran Vía                         5617293
Calle Princesa                   3283849
Calle Toledo                     2821574
Plaza del Emperador Carlos V     2185960
Calle Génova                     1759394
Carrera de San Jerónimo          1215547
Ronda de Valencia                1160608
Alberto Aguilera                 1149314
Calle Atocha                     1046587
Name: PEATONES, dtype: int64

## ¿A qué hora hay más peatones?

Pasos:

1. Agrupa los registros por hora.

2. Calcula el total de peatones registrados en cada hora.

3. Ordena los resultados de mayor a menor.

4. Identifica la hora con mayor y menor número total de peatones.

In [228]:
# 1. Crear una columna con la hora
# Como FECHA contiene la fecha y la hora, podemos extraer la hora con .dt.hour
df_1["HORA_DIA"] = df_1["FECHA"].dt.hour

# 2. Calcular el total de peatones por hora
peatones_hora = df_1.groupby("HORA_DIA")["PEATONES"].sum()

# 3. Ordenar de mayor a menor
peatones_hora_ordenado = peatones_hora.sort_values(
    ascending=False
)

print(peatones_hora_ordenado)

HORA_DIA
20    4469552
21    4169983
19    4013067
18    3304044
14    3059466
22    2906280
13    2815571
15    2751493
17    2732509
16    2488252
12    2398073
23    1911736
11    1650985
0     1253469
10    1217730
9      931989
1      846635
8      678473
2      592709
7      475331
3      426225
4      384638
5      335120
6      330353
Name: PEATONES, dtype: int64