# Exploración y manipulación de Datos con Pandas

La exploración y manipulación de datos consiste en leer, organizar y modificar información almacenada en archivos o bases de datos. 
Para organizar nuestro trabajo, vamos a tener una carpeta llamada `Data` con los ficheros de datos de trabajo.

Python utiliza principalmente la biblioteca **Pandas** para la exploración y manipulación de datos y se importa mediante:

```python
import pandas as pd
```

donde `pd` es un alias, es decir, un nombre abreviado que nosotros elegimos para referirnos a la librería pandas.

La estructura principal de Pandas es el **DataFrame**, una tabla con filas y columnas similar a una hoja de cálculo (Excel, Number, Google sheet,...).
Podemos crear un DataFrame manualmente o importarlo desde un fichero.

## Crear un DataFrame manualmente:

In [299]:
import pandas as pd

datos = {
    "Nombre": ["Ana", "Luis", "Marta"],
    "Edad": [24,31,28],
    "Ciudad": ["Madrid","Sevilla","Valencia"]
}

df = pd.DataFrame(datos)

df

  Nombre  Edad    Ciudad
0    Ana    24    Madrid
1   Luis    31   Sevilla
2  Marta    28  Valencia

## Importar los datos desde un fichero


A la vez que importamos los datos, se crea el dataframe. 
Los datos pueden estar almacenados en distintos formatos, nosotros vamos a trabajar con ficheros cvs y excel. 


***Leer un archivo CSV***

Un archivo CSV es un texto donde las columnas están separadas por comas.

In [302]:
df = pd.read_csv("./Data/Nombre_Edad_Ciudad.csv")
# número de filas y columnas
df.shape

(6, 3)

***Leer un archivo Excel***

In [305]:
import openpyxl
df = pd.read_excel("./Data/Nombre_Edad_Ciudad.xlsx")
# número de filas y columnas
df.shape

(6, 3)

In [307]:
df

     Nombre  Edad    Ciudad
0     Sonia    24    Madrid
1    Carmen    31   Sevilla
2     Marta    28  Valencia
3      Jose    40   Segovia
4    Nieves    16    Madrid
5  Carlitos    12    Madrid

## Explorar un data frame

El comando `df.info()` nos da un resumen general del DataFrame que nos da la estructura, tipos y valores no nulos.

In [311]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  6 non-null      object
 1   Edad    6 non-null      int64
 2   Ciudad  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

Para saber cuáles son las columnas numéricas y sus cuartiles, medias,... podemos hacer un `df.describe()` y nos mostrará la siguiente información. 

- `count`es el número de **valores no nulos**.
- `mean` es la **media aritmética**.
- `std`	es la **desviación estándar**. Una `std` pequeña implica valores bastante agrupados y `std` grande implica valores más dispersos.
- `min`	es el **valor mínimo**.
- `25%`	es el **primer cuartil** (Q1). El 25 % de los datos están por debajo de Q1.
- `50%`	es la **mediana** (Q2). El 50 % de los datos están por debajo de Q2.
- `75%`	es el **tercer cuartil** (Q3). El 75 % de los datos están por debajo de Q3.
- `max`	es el valor **máximo**.

In [314]:
df.describe()

            Edad
count   6.000000
mean   25.166667
std    10.206207
min    12.000000
25%    18.000000
50%    26.000000
75%    30.250000
max    40.000000

Si además de las variables numéricas queremos incluir las variables categóricas (texto) hacemos `df.describe(include="all")`. Esto nos permite obtener información  de las variables categóricas donde:

- `count` es el número de **valores no nulos**.
- `unique` es el número de **valores diferentes**.
- `top`	es el valor que **aparece más veces**. Si todos aparecen una vez, toma el primero.
- `freq` es el **número de veces que aparece top**

In [317]:
df.describe(include="all")

       Nombre       Edad  Ciudad
count       6   6.000000       6
unique      6        NaN       4
top     Sonia        NaN  Madrid
freq        1        NaN       3
mean      NaN  25.166667     NaN
std       NaN  10.206207     NaN
min       NaN  12.000000     NaN
25%       NaN  18.000000     NaN
50%       NaN  26.000000     NaN
75%       NaN  30.250000     NaN
max       NaN  40.000000     NaN

## Explorar filas y columnas

Una tabla puede tener un gran número de entradas o filas, es por ello que se recomienda explorar una parte del dataframe con `head` y `tail`.

In [320]:
df.head()  # Primeras filas

   Nombre  Edad    Ciudad
0   Sonia    24    Madrid
1  Carmen    31   Sevilla
2   Marta    28  Valencia
3    Jose    40   Segovia
4  Nieves    16    Madrid

In [322]:
df.tail()  # Últimas filas

     Nombre  Edad    Ciudad
1    Carmen    31   Sevilla
2     Marta    28  Valencia
3      Jose    40   Segovia
4    Nieves    16    Madrid
5  Carlitos    12    Madrid

También podemos seleccionar unas filas concretas con `loc`y `iloc`

- .loc: Selecciona columnas usando sus **nombres** o **etiquetas**.
- .iloc: Selecciona filas y/o columnas usando su **posición numérica** (enteros del 0 en adelante).

Nota: Los dos puntos ':' significa que trabajamos en un rango. Por ejemplo, `0:2` toma todos los números comprendidos entre `0` y `2` y tener los dos puntos sin números definiendo el rango `:`quiere decir que toma el rango completo.

In [325]:
df.loc[3, "Nombre"]   # Celda

'Jose'

In [327]:
df.loc[3, ["Nombre","Edad"]]   # fila 3 y columnas "Nombre","Edad"

Nombre    Jose
Edad        40
Name: 3, dtype: object

In [329]:
df.loc[3]      # fila 3  (todas las columnas)

Nombre       Jose
Edad           40
Ciudad    Segovia
Name: 3, dtype: object

In [331]:
df.loc[:, ["Nombre","Edad"]]    # Todas las filas y columnas "Nombre","Edad"

     Nombre  Edad
0     Sonia    24
1    Carmen    31
2     Marta    28
3      Jose    40
4    Nieves    16
5  Carlitos    12

In [333]:
df.iloc[3,0]  # Celda

'Jose'

In [335]:
df.iloc[3, [0,1]]      # fila 3 y columnas "Nombre","Edad"

Nombre    Jose
Edad        40
Name: 3, dtype: object

In [337]:
df.iloc[3]

Nombre       Jose
Edad           40
Ciudad    Segovia
Name: 3, dtype: object

In [339]:
df.iloc[0:2]     # Filas 0:2 y todas las columnas

   Nombre  Edad   Ciudad
0   Sonia    24   Madrid
1  Carmen    31  Sevilla

In [341]:
df.iloc[:, [0, 1]]

     Nombre  Edad
0     Sonia    24
1    Carmen    31
2     Marta    28
3      Jose    40
4    Nieves    16
5  Carlitos    12

Hay ficheros que pueden tener un gran número de columnas, en este caso es interesante listar las columnas que tenemos.

In [344]:
df.columns

Index(['Nombre', 'Edad', 'Ciudad'], dtype='object')

El resultado de `df.columns` es una lista indexada, por lo tanto podemos acceder a un elemento concreto de la lista mediante su índice.

In [347]:
df.columns[2]

'Ciudad'

Otra forma de ver los datos de algunas columnas concretas es mediante los corchetes.

In [350]:
df["Edad"]        # Una columna

0    24
1    31
2    28
3    40
4    16
5    12
Name: Edad, dtype: int64

In [352]:
df[["Nombre","Edad"]]   # Varias columnas

     Nombre  Edad
0     Sonia    24
1    Carmen    31
2     Marta    28
3      Jose    40
4    Nieves    16
5  Carlitos    12

## Filtrar

Se **filtran** las filas u observaciones que cumplen una determinada restricción.

In [356]:
df[df["Edad"]>=30]

   Nombre  Edad   Ciudad
1  Carmen    31  Sevilla
3    Jose    40  Segovia

In [358]:
df[(df["Edad"] >= 20) & (df["Edad"] < 40)]

   Nombre  Edad    Ciudad
0   Sonia    24    Madrid
1  Carmen    31   Sevilla
2   Marta    28  Valencia

In [360]:
df[(df["Ciudad"] == "Madrid")]

     Nombre  Edad  Ciudad
0     Sonia    24  Madrid
4    Nieves    16  Madrid
5  Carlitos    12  Madrid

## Ordenar

Se pueden **ordenar** los datos por determinadas columnas.

In [363]:
df.sort_values("Edad")

     Nombre  Edad    Ciudad
5  Carlitos    12    Madrid
4    Nieves    16    Madrid
0     Sonia    24    Madrid
2     Marta    28  Valencia
1    Carmen    31   Sevilla
3      Jose    40   Segovia

In [365]:
df.sort_values("Edad", ascending=False)

     Nombre  Edad    Ciudad
3      Jose    40   Segovia
1    Carmen    31   Sevilla
2     Marta    28  Valencia
0     Sonia    24    Madrid
4    Nieves    16    Madrid
5  Carlitos    12    Madrid

## Crear nuevas columnas

Podemos crear nuevas columnas resultado de realizar cálculos.

In [369]:
df["Menor_edad"] = df["Edad"]>=18
df

     Nombre  Edad    Ciudad  Menor_edad
0     Sonia    24    Madrid        True
1    Carmen    31   Sevilla        True
2     Marta    28  Valencia        True
3      Jose    40   Segovia        True
4    Nieves    16    Madrid       False
5  Carlitos    12    Madrid       False

## Eliminar columnas

In [372]:
df = df.drop(columns = "Menor_edad")
df

     Nombre  Edad    Ciudad
0     Sonia    24    Madrid
1    Carmen    31   Sevilla
2     Marta    28  Valencia
3      Jose    40   Segovia
4    Nieves    16    Madrid
5  Carlitos    12    Madrid

## Renombrar columnas

In [375]:
df = df.rename(columns = {"Ciudad":"Población"})
df

     Nombre  Edad Población
0     Sonia    24    Madrid
1    Carmen    31   Sevilla
2     Marta    28  Valencia
3      Jose    40   Segovia
4    Nieves    16    Madrid
5  Carlitos    12    Madrid

## Valores nulos

En Python/pandas conviene distinguir `None`, `NaN` y `nan`, 
que representan *dato ausente*, no son exactamente lo mismo.
- `None` es el valor especial de Python que significa “no hay valor”.
- `NaN` y `nan` significa Not a Number (“no es un número”).

In [379]:
df.isnull()   # equivalente a df.isna()

   Nombre   Edad  Población
0   False  False      False
1   False  False      False
2   False  False      False
3   False  False      False
4   False  False      False
5   False  False      False

In [381]:
# df["Edad"].isna()
pd.isna(df["Edad"])

0    False
1    False
2    False
3    False
4    False
5    False
Name: Edad, dtype: bool

En dataframes muy grandes es muy interesante contar los valores ausentes

In [384]:
df.isnull().sum()

Nombre       0
Edad         0
Población    0
dtype: int64

## Añadir una fila con un valor nulo

Para añadir una fila, decimos que pasada la última fila `len(df)`, se asigna una lista de datos. En este caso, voy a aprovechar que añado una fila para dejar una celda sin dato. Por ejemplo, dejamos la edad sin conocer.

Aviso: cada vez que ejecutes esta intrucción, se añade una fila nueva.

In [387]:
df.loc[len(df)] = ["Amelia", None, "Toledo"]
df

     Nombre  Edad Población
0     Sonia    24    Madrid
1    Carmen    31   Sevilla
2     Marta    28  Valencia
3      Jose    40   Segovia
4    Nieves    16    Madrid
5  Carlitos    12    Madrid
6    Amelia  None    Toledo

## Eliminar filas con valores nulos

En ocasiones, no nos interesan las filas que no son completas. En estos casos se eliminan dichas filas.

In [391]:
df.dropna()

     Nombre Edad Población
0     Sonia   24    Madrid
1    Carmen   31   Sevilla
2     Marta   28  Valencia
3      Jose   40   Segovia
4    Nieves   16    Madrid
5  Carlitos   12    Madrid

Aunque yo personalmente prefiero crear un nuevo dataframe copiando únicamente las filas y/o columnas que me iteresan.

In [394]:
df_1 = df[["Nombre","Edad"]].copy()
df_1

     Nombre  Edad
0     Sonia    24
1    Carmen    31
2     Marta    28
3      Jose    40
4    Nieves    16
5  Carlitos    12
6    Amelia  None

In [396]:
df_2 = df[(df["Población"] == "Madrid")].copy()

## Operaciones sobre una columna numérica

A continuación ponemos una muestra, para más detalle se puede consultar la documentación de Python (https://docs.python.org/es/3.14/builtins/functions.html).

In [399]:
df["Edad"].mean()

25.166666666666668

In [401]:
df["Edad"].max()

40

In [403]:
df["Edad"].min()

12

In [405]:
df["Edad"].sum()

151

## Agrupar

En un DataFrame, `groupby` sirve para agrupar las filas que tienen un mismo valor en una columna y después realizar alguna operación sobre cada grupo. Por ejmplo, podemos agrupar por población. Es decir, `groupby` divide el DataFrame en grupos según los valores de una o varias columnas y permite aplicar una operación a cada grupo.

```python
# Sintáxis general
df.groupby("columna")["columna_a_analizar"].operación()
```

```python
# Ejemplo
df.groupby("Población")
```

Esto crea los grupos, pero todavía no vemos un resultado útil. Tenemos que decir qué queremos hacer con cada grupo. 
Por ejemplo, queremos calcular la media edad.

In [418]:
df.groupby("Población")["Edad"].mean()

Población
Madrid      17.333333
Segovia          40.0
Sevilla          31.0
Toledo            NaN
Valencia         28.0
Name: Edad, dtype: object

In [420]:
df

     Nombre  Edad Población
0     Sonia    24    Madrid
1    Carmen    31   Sevilla
2     Marta    28  Valencia
3      Jose    40   Segovia
4    Nieves    16    Madrid
5  Carlitos    12    Madrid
6    Amelia  None    Toledo

Podemos calcular varias operaciones

In [427]:
df.groupby("Población")["Edad"].agg(["count", "mean", "min", "max"])

           count       mean   min   max
Población
Madrid         3  17.333333  12.0  24.0
Segovia        1       40.0  40.0  40.0
Sevilla        1       31.0  31.0  31.0
Toledo         0        NaN   NaN   NaN
Valencia       1       28.0  28.0  28.0

También podemos contar personas. Aquí debemos seleccionar otra columna como `Nombre`

In [425]:
df.groupby("Población")["Nombre"].count()

Población
Madrid      3
Segovia     1
Sevilla     1
Toledo      1
Valencia    1
Name: Nombre, dtype: int64

## Guardar datos

In [408]:
# Guardar como CSV:
# index=False le dice a Pandas que no guarde el índice del DataFrame como una columna adicional en el CSV.

df.to_csv("./Data/nuevo.csv", index=False)  

# Guardar como Excel:

df.to_excel("./Data/nuevo.xlsx", index=False)

In [412]:
df

     Nombre  Edad Población
0     Sonia    24    Madrid
1    Carmen    31   Sevilla
2     Marta    28  Valencia
3      Jose    40   Segovia
4    Nieves    16    Madrid
5  Carlitos    12    Madrid
6    Amelia  None    Toledo