# Exploración y manipulación de Datos con Pandas

La manipulación de datos consiste en leer, organizar y modificar información almacenada en archivos o bases de datos. Python utiliza principalmente la biblioteca **Pandas** para estas tareas.

Para importar esta biblioteca escribimos

```python
import pandas as pd
```

La estructura principal de Pandas es el **DataFrame**, una tabla con filas y columnas similar a una hoja de cálculo (Excel, Number, Google sheet,...).
Podemos crear un DataFrame manualmente o importarlo desde un fichero.

## Crear un DataFrame manualmente:

In [315]:
import pandas as pd

datos = {
    "Nombre": ["Ana", "Luis", "Marta"],
    "Edad": [24,31,28],
    "Ciudad": ["Madrid","Sevilla","Valencia"]
}

df = pd.DataFrame(datos)

print(df)

  Nombre  Edad    Ciudad
0    Ana    24    Madrid
1   Luis    31   Sevilla
2  Marta    28  Valencia

## Importar los datos desde un fichero


A la vez que importamos los datos, creamos el dataframe. Los datos pueden estar almacenados en distintos formatos. Los más habituales son:

***Leer un archivo CSV***

Un archivo CSV es un texto donde las columnas están separadas por comas.

In [317]:
df = pd.read_csv("./Data/Nombre_Edad_Ciudad.csv")
df.head()    # Muestra las primeras filas

   Nombre  Edad    Ciudad
0   Sonia    24    Madrid
1  Carmen    31   Sevilla
2  Conchi    28  Valencia
3    Jose    40   Segovia

***Leer un archivo Excel***

In [319]:
import openpyxl
df = pd.read_excel("./Data/Nombre_Edad_Ciudad.xlsx")
df.head()    # Muestra las primeras filas

   Nombre  Edad    Ciudad
0   Sonia    24    Madrid
1  Carmen    31   Sevilla
2   Marta    28  Valencia
3    Jose    40   Segovia

## Explorar filas y columnas

Una tabla puede tener un gran número de entradas o filas, es por ello que se recomienda explorar una parte del dataframe con `head` y `tail`.

In [321]:
df.head()  # Primeras filas

   Nombre  Edad    Ciudad
0   Sonia    24    Madrid
1  Carmen    31   Sevilla
2   Marta    28  Valencia
3    Jose    40   Segovia

In [322]:
df.tail()  # Últimas filas

   Nombre  Edad    Ciudad
0   Sonia    24    Madrid
1  Carmen    31   Sevilla
2   Marta    28  Valencia
3    Jose    40   Segovia

Puede interesarnos una  varias columnas. Podemos seleccionar el número de columnas que queramos mediante los corchetes.

In [324]:
df["Nombre"]

0     Sonia
1    Carmen
2     Marta
3      Jose
Name: Nombre, dtype: object

In [325]:
df[["Nombre","Edad"]]

   Nombre  Edad
0   Sonia    24
1  Carmen    31
2   Marta    28
3    Jose    40

También podemos seleccionar unas filas concretas

In [327]:
df.iloc[0:2]

   Nombre  Edad   Ciudad
0   Sonia    24   Madrid
1  Carmen    31  Sevilla

## Filtrar

Se **filtran** las filas u observaciones que cumplen una determinada restricción.

In [330]:
df[df["Edad"]>=30]

   Nombre  Edad   Ciudad
1  Carmen    31  Sevilla
3    Jose    40  Segovia

In [331]:
df[(df["Edad"]>=20) & (df["Edad"]< 40)]

   Nombre  Edad    Ciudad
0   Sonia    24    Madrid
1  Carmen    31   Sevilla
2   Marta    28  Valencia

## Ordenar

Se pueden **ordenar** los datos por determinadas columnas.

In [333]:
df.sort_values("Edad")

   Nombre  Edad    Ciudad
0   Sonia    24    Madrid
2   Marta    28  Valencia
1  Carmen    31   Sevilla
3    Jose    40   Segovia

In [334]:
df.sort_values("Edad", ascending=False)

   Nombre  Edad    Ciudad
3    Jose    40   Segovia
1  Carmen    31   Sevilla
2   Marta    28  Valencia
0   Sonia    24    Madrid

## Crear nuevas columnas

Podemos crear nuevas columnas resultado de
 realizar cálculos.

In [337]:
df["Menor_edad"] = df["Edad"]>=18
df

   Nombre  Edad    Ciudad  Menor_edad
0   Sonia    24    Madrid        True
1  Carmen    31   Sevilla        True
2   Marta    28  Valencia        True
3    Jose    40   Segovia        True

## Eliminar columnas

In [339]:
df = df.drop(columns="Menor_edad")
df

   Nombre  Edad    Ciudad
0   Sonia    24    Madrid
1  Carmen    31   Sevilla
2   Marta    28  Valencia
3    Jose    40   Segovia

## Renombrar columnas

In [341]:
df = df.rename(columns={"Ciudad":"Población"})
df

   Nombre  Edad Población
0   Sonia    24    Madrid
1  Carmen    31   Sevilla
2   Marta    28  Valencia
3    Jose    40   Segovia

## Valores nulos

In [343]:
df.isnull()

   Nombre   Edad  Población
0   False  False      False
1   False  False      False
2   False  False      False
3   False  False      False

## Eliminar filas con datos vacíos:

In [345]:
df.dropna()

   Nombre  Edad Población
0   Sonia    24    Madrid
1  Carmen    31   Sevilla
2   Marta    28  Valencia
3    Jose    40   Segovia

## Operaciones sobre una columna numérica

In [347]:
df["Edad"].mean()

30.75

In [348]:
df["Edad"].max()

40

In [349]:
df["Edad"].min()

24

In [350]:
df["Edad"].sum()

123

## Guardar datos

In [352]:
# Guardar como CSV:

df.to_csv("./Data/nuevo.csv", index=False)

# Guardar como Excel:

df.to_excel("./Data/nuevo.xlsx", index=False)