# Exploración y manipulación de Datos con Pandas

La exploración y manipulación de datos consiste en leer, organizar y modificar información almacenada en archivos o bases de datos. 
Para organizar nuestro trabajo, vamos a tener una carpeta llamada `Data` con los ficheros de datos de trabajo.

Python utiliza principalmente la biblioteca **Pandas** para la exploración y manipulación de datos y se importa mediante:

```python
import pandas as pd
```

donde `pd` es un alias, es decir, un nombre abreviado que nosotros elegimos para referirnos a la librería pandas.

La estructura principal de Pandas es el **DataFrame**, una tabla con filas y columnas similar a una hoja de cálculo (Excel, Number, Google sheet,...).
Podemos crear un DataFrame manualmente o importarlo desde un fichero.

## Crear un DataFrame manualmente:

In [83]:
import pandas as pd

datos = {
    "Nombre": ["Ana", "Luis", "Marta"],
    "Edad": [24,31,28],
    "Ciudad": ["Madrid","Sevilla","Valencia"]
}

df = pd.DataFrame(datos)

df

  Nombre  Edad    Ciudad
0    Ana    24    Madrid
1   Luis    31   Sevilla
2  Marta    28  Valencia

## Importar los datos desde un fichero


A la vez que importamos los datos, se crea el dataframe. 
Los datos pueden estar almacenados en distintos formatos, nosotros vamos a trabajar con ficheros cvs y excel. 


***Leer un archivo CSV***

Un archivo CSV es un texto donde las columnas están separadas por comas.

In [85]:
df = pd.read_csv("./Data/Nombre_Edad_Ciudad.csv")
# número de filas y columnas
df.shape

(6, 3)

***Leer un archivo Excel***

In [87]:
import openpyxl
df = pd.read_excel("./Data/Nombre_Edad_Ciudad.xlsx")
# número de filas y columnas
df.shape

(6, 3)

In [88]:
df

     Nombre  Edad    Ciudad
0     Sonia    24    Madrid
1    Carmen    31   Sevilla
2     Marta    28  Valencia
3      Jose    40   Segovia
4    Nieves    16    Madrid
5  Carlitos    12    Madrid

## Explorar un data frame

El comando `df.info()` nos da un resumen general del DataFrame que nos da la estructura, tipos y valores no nulos.

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  6 non-null      object
 1   Edad    6 non-null      int64
 2   Ciudad  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

## Seleccionar filas y columnas

También podemos seleccionar unas filas concretas con `loc`y `iloc`

- .loc: Selecciona columnas usando sus **nombres** o **etiquetas**.
- .iloc: Selecciona filas y/o columnas usando su **posición numérica** (enteros del 0 en adelante).

Nota: Los dos puntos ':' significa que trabajamos en un rango. Por ejemplo, `0:2` toma todos los números comprendidos entre `0` y `2` y tener los dos puntos sin números definiendo el rango `:`quiere decir que toma el rango completo.

In [94]:
df.loc[3, "Nombre"]   # Celda

'Jose'

In [95]:
df.loc[3, ["Nombre","Edad"]]   # fila 3 y columnas "Nombre","Edad"

Nombre    Jose
Edad        40
Name: 3, dtype: object

In [96]:
df.loc[3]      # fila 3  (todas las columnas)

Nombre       Jose
Edad           40
Ciudad    Segovia
Name: 3, dtype: object

In [97]:
df.loc[:, ["Nombre","Edad"]]    # Todas las filas y columnas "Nombre","Edad"

     Nombre  Edad
0     Sonia    24
1    Carmen    31
2     Marta    28
3      Jose    40
4    Nieves    16
5  Carlitos    12

In [98]:
df.iloc[3,0]  # Celda

'Jose'

In [99]:
df.iloc[3, [0,1]]      # fila 3 y columnas "Nombre","Edad"

Nombre    Jose
Edad        40
Name: 3, dtype: object

In [100]:
df.iloc[3]

Nombre       Jose
Edad           40
Ciudad    Segovia
Name: 3, dtype: object

In [101]:
df.iloc[0:2]     # Filas 0:2 y todas las columnas

   Nombre  Edad   Ciudad
0   Sonia    24   Madrid
1  Carmen    31  Sevilla

In [102]:
df.iloc[:, [0, 1]]

     Nombre  Edad
0     Sonia    24
1    Carmen    31
2     Marta    28
3      Jose    40
4    Nieves    16
5  Carlitos    12

Hay ficheros que pueden tener un gran número de columnas, en este caso es interesante listar las columnas que tenemos.

In [104]:
df.columns

Index(['Nombre', 'Edad', 'Ciudad'], dtype='object')

El resultado de `df.columns` es una lista indexada, por lo tanto podemos acceder a un elemento concreto de la lista mediante su índice.

In [106]:
df.columns[2]

'Ciudad'

Otra forma de ver los datos de algunas columnas concretas es mediante los corchetes.

In [108]:
df["Edad"]        # Una columna

0    24
1    31
2    28
3    40
4    16
5    12
Name: Edad, dtype: int64

In [109]:
df[["Nombre","Edad"]]   # Varias columnas

     Nombre  Edad
0     Sonia    24
1    Carmen    31
2     Marta    28
3      Jose    40
4    Nieves    16
5  Carlitos    12

## Filtrar

Se **filtran** las filas u observaciones que cumplen una determinada restricción.

In [112]:
df[df["Edad"]>=30]

   Nombre  Edad   Ciudad
1  Carmen    31  Sevilla
3    Jose    40  Segovia

In [113]:
df[(df["Edad"] >= 20) & (df["Edad"] < 40)]

   Nombre  Edad    Ciudad
0   Sonia    24    Madrid
1  Carmen    31   Sevilla
2   Marta    28  Valencia

In [114]:
df[(df["Ciudad"] == "Madrid")]

     Nombre  Edad  Ciudad
0     Sonia    24  Madrid
4    Nieves    16  Madrid
5  Carlitos    12  Madrid

## Ordenar

Se pueden **ordenar** los datos por determinadas columnas.

In [116]:
df.sort_values("Edad")

     Nombre  Edad    Ciudad
5  Carlitos    12    Madrid
4    Nieves    16    Madrid
0     Sonia    24    Madrid
2     Marta    28  Valencia
1    Carmen    31   Sevilla
3      Jose    40   Segovia

In [117]:
df.sort_values("Edad", ascending=False)

     Nombre  Edad    Ciudad
3      Jose    40   Segovia
1    Carmen    31   Sevilla
2     Marta    28  Valencia
0     Sonia    24    Madrid
4    Nieves    16    Madrid
5  Carlitos    12    Madrid

## Crear nuevas columnas

Podemos crear nuevas columnas resultado de realizar cálculos.

In [120]:
df["Menor_edad"] = df["Edad"]>=18
df

     Nombre  Edad    Ciudad  Menor_edad
0     Sonia    24    Madrid        True
1    Carmen    31   Sevilla        True
2     Marta    28  Valencia        True
3      Jose    40   Segovia        True
4    Nieves    16    Madrid       False
5  Carlitos    12    Madrid       False

## Renombrar columnas

In [122]:
df = df.rename(columns = {"Ciudad":"Población"})
df

     Nombre  Edad Población  Menor_edad
0     Sonia    24    Madrid        True
1    Carmen    31   Sevilla        True
2     Marta    28  Valencia        True
3      Jose    40   Segovia        True
4    Nieves    16    Madrid       False
5  Carlitos    12    Madrid       False

## Seleccionar ciertas columnas

In [124]:
df_1 = df[["Nombre","Edad"]].copy()
df_1

     Nombre  Edad
0     Sonia    24
1    Carmen    31
2     Marta    28
3      Jose    40
4    Nieves    16
5  Carlitos    12

In [125]:
df_2 = df[(df["Población"] == "Madrid")].copy()

## Operaciones sobre una columna numérica

A continuación ponemos una muestra, para más detalle se puede consultar la documentación de Python (https://docs.python.org/es/3.14/builtins/functions.html).

In [127]:
df["Edad"].mean()

25.166666666666668

In [128]:
df["Edad"].max()

40

In [129]:
df["Edad"].min()

12

In [130]:
df["Edad"].sum()

151

## Agrupar

En un DataFrame, `groupby` sirve para agrupar las filas que tienen un mismo valor en una columna y después realizar alguna operación sobre cada grupo. Por ejmplo, podemos agrupar por población. Es decir, `groupby` divide el DataFrame en grupos según los valores de una o varias columnas y permite aplicar una operación a cada grupo.

```python
# Sintáxis general
df.groupby("columna")["columna_a_analizar"].operación()
```

```python
# Ejemplo
df.groupby("Población")
```

Esto crea los grupos, pero todavía no vemos un resultado útil. Tenemos que decir qué queremos hacer con cada grupo. 
Por ejemplo, queremos calcular la media edad.

In [132]:
df.groupby("Población")["Edad"].mean()

Población
Madrid      17.333333
Segovia     40.000000
Sevilla     31.000000
Valencia    28.000000
Name: Edad, dtype: float64

In [133]:
df

     Nombre  Edad Población  Menor_edad
0     Sonia    24    Madrid        True
1    Carmen    31   Sevilla        True
2     Marta    28  Valencia        True
3      Jose    40   Segovia        True
4    Nieves    16    Madrid       False
5  Carlitos    12    Madrid       False

Podemos calcular varias operaciones

In [135]:
df.groupby("Población")["Edad"].agg(["count", "mean", "min", "max"])

           count       mean  min  max
Población
Madrid         3  17.333333   12   24
Segovia        1  40.000000   40   40
Sevilla        1  31.000000   31   31
Valencia       1  28.000000   28   28

También podemos contar personas. Aquí debemos seleccionar otra columna como `Nombre`

In [137]:
df.groupby("Población")["Nombre"].count()

Población
Madrid      3
Segovia     1
Sevilla     1
Valencia    1
Name: Nombre, dtype: int64

## Guardar datos

In [139]:
# Guardar como CSV:
# index=False le dice a Pandas que no guarde el índice del DataFrame como una columna adicional en el CSV.

df.to_csv("./Data/nuevo.csv", index=False)  

# Guardar como Excel:

df.to_excel("./Data/nuevo.xlsx", index=False)

In [140]:
df

     Nombre  Edad Población  Menor_edad
0     Sonia    24    Madrid        True
1    Carmen    31   Sevilla        True
2     Marta    28  Valencia        True
3      Jose    40   Segovia        True
4    Nieves    16    Madrid       False
5  Carlitos    12    Madrid       False