# Exploración y manipulación de Datos con Pandas

La manipulación de datos consiste en leer, organizar y modificar información almacenada en archivos o bases de datos. Python utiliza principalmente la biblioteca **Pandas** para estas tareas.

Para importar esta biblioteca escribimos

```python
import pandas as pd
```

La estructura principal de Pandas es el **DataFrame**, una tabla con filas y columnas similar a una hoja de cálculo (Excel, Number, Google sheet,...).
Podemos crear un DataFrame manualmente o importarlo desde un fichero.

## Crear un DataFrame manualmente:

In [283]:
import pandas as pd

datos = {
    "Nombre": ["Ana", "Luis", "Marta"],
    "Edad": [24,31,28],
    "Ciudad": ["Madrid","Sevilla","Valencia"]
}

df = pd.DataFrame(datos)

print(df)

  Nombre  Edad    Ciudad
0    Ana    24    Madrid
1   Luis    31   Sevilla
2  Marta    28  Valencia

## Importar los datos desde un fichero


A la vez que importamos los datos, se crea el dataframe. 
Los datos pueden estar almacenados en distintos formatos, nosotros vamos a trabajar con ficheros cvs y excel. 


***Leer un archivo CSV***

Un archivo CSV es un texto donde las columnas están separadas por comas.

In [285]:
df_excel = pd.read_csv("./Data/Nombre_Edad_Ciudad.csv")
# número de filas y columnas
print(df.shape)

(3, 3)

***Leer un archivo Excel***

In [287]:
import openpyxl
df = pd.read_excel("./Data/Nombre_Edad_Ciudad.xlsx")
# número de filas y columnas
print(df.shape)

(6, 3)

## Explorar filas y columnas

Una tabla puede tener un gran número de entradas o filas, es por ello que se recomienda explorar una parte del dataframe con `head` y `tail`.

In [289]:
df.head()  # Primeras filas

   Nombre  Edad    Ciudad
0   Sonia    24    Madrid
1  Carmen    31   Sevilla
2   Marta    28  Valencia
3    Jose    40   Segovia
4  Nieves    16    Madrid

In [290]:
df.tail()  # Últimas filas

     Nombre  Edad    Ciudad
1    Carmen    31   Sevilla
2     Marta    28  Valencia
3      Jose    40   Segovia
4    Nieves    16    Madrid
5  Carlitos    12    Madrid

También puede tener un gran número de columnas. en este caso es interesante listar las columnas que tenemos.

In [292]:
print(df.columns)

Index(['Nombre', 'Edad', 'Ciudad'], dtype='object')

Además, puede interesarnos ver los datos de algunas columnas concretas. Podemos seleccionar el número de columnas que queramos mediante los corchetes.

In [294]:
df[["Nombre","Edad"]]

     Nombre  Edad
0     Sonia    24
1    Carmen    31
2     Marta    28
3      Jose    40
4    Nieves    16
5  Carlitos    12

También podemos seleccionar unas filas concretas

In [296]:
df.iloc[0:2]

   Nombre  Edad   Ciudad
0   Sonia    24   Madrid
1  Carmen    31  Sevilla

## Filtrar

Se **filtran** las filas u observaciones que cumplen una determinada restricción.

In [299]:
df[df["Edad"]>=30]

   Nombre  Edad   Ciudad
1  Carmen    31  Sevilla
3    Jose    40  Segovia

In [300]:
df[(df["Edad"] >= 20) & (df["Edad"] < 40)]

   Nombre  Edad    Ciudad
0   Sonia    24    Madrid
1  Carmen    31   Sevilla
2   Marta    28  Valencia

In [301]:
df[(df["Ciudad"] == "Madrid")]

     Nombre  Edad  Ciudad
0     Sonia    24  Madrid
4    Nieves    16  Madrid
5  Carlitos    12  Madrid

## Ordenar

Se pueden **ordenar** los datos por determinadas columnas.

In [303]:
df.sort_values("Edad")

     Nombre  Edad    Ciudad
5  Carlitos    12    Madrid
4    Nieves    16    Madrid
0     Sonia    24    Madrid
2     Marta    28  Valencia
1    Carmen    31   Sevilla
3      Jose    40   Segovia

In [304]:
df.sort_values("Edad", ascending=False)

     Nombre  Edad    Ciudad
3      Jose    40   Segovia
1    Carmen    31   Sevilla
2     Marta    28  Valencia
0     Sonia    24    Madrid
4    Nieves    16    Madrid
5  Carlitos    12    Madrid

## Crear nuevas columnas

Podemos crear nuevas columnas resultado de realizar cálculos.

In [307]:
df["Menor_edad"] = df["Edad"]>=18
df

     Nombre  Edad    Ciudad  Menor_edad
0     Sonia    24    Madrid        True
1    Carmen    31   Sevilla        True
2     Marta    28  Valencia        True
3      Jose    40   Segovia        True
4    Nieves    16    Madrid       False
5  Carlitos    12    Madrid       False

## Eliminar columnas

In [309]:
df = df.drop(columns = "Menor_edad")
df

     Nombre  Edad    Ciudad
0     Sonia    24    Madrid
1    Carmen    31   Sevilla
2     Marta    28  Valencia
3      Jose    40   Segovia
4    Nieves    16    Madrid
5  Carlitos    12    Madrid

## Renombrar columnas

In [311]:
df = df.rename(columns = {"Ciudad":"Población"})
df

     Nombre  Edad Población
0     Sonia    24    Madrid
1    Carmen    31   Sevilla
2     Marta    28  Valencia
3      Jose    40   Segovia
4    Nieves    16    Madrid
5  Carlitos    12    Madrid

## Añadir una fila con un valor nulo

Para añadir una fila, decimos que pasada la última fila (len(df)) se edita df.loc[ ] y se le asigna una lista de datos. En este caso, voy a aprovechar que añado una fila para dejar una celda sin dato. Por ejemplo, dejamos la edad sin conocer.

Aviso: cada vez que ejecutes esta intrucción, se añade una fila nueva.

In [313]:
df.loc[len(df)] = ["Amelia", None, "Toledo"]

## Valores nulos

In [315]:
df.isnull()

   Nombre   Edad  Población
0   False  False      False
1   False  False      False
2   False  False      False
3   False  False      False
4   False  False      False
5   False  False      False
6   False   True      False

## Eliminar filas con datos vacíos:

En ocasiones, no nos interesan las filas que no son completas. En estos casos se eliminan dichas filas.

In [318]:
df.dropna()

     Nombre Edad Población
0     Sonia   24    Madrid
1    Carmen   31   Sevilla
2     Marta   28  Valencia
3      Jose   40   Segovia
4    Nieves   16    Madrid
5  Carlitos   12    Madrid

## Operaciones sobre una columna numérica

A continuación ponemos una muestra, para más detalle se puede consultar la documentación de Python (https://docs.python.org/es/3.14/builtins/functions.html).

In [320]:
df["Edad"].mean()

25.166666666666668

In [321]:
df["Edad"].max()

40

In [322]:
df["Edad"].min()

12

In [323]:
df["Edad"].sum()

151

## Guardar datos

In [325]:
# Guardar como CSV:

df.to_csv("./Data/nuevo.csv", index=False)

# Guardar como Excel:

df.to_excel("./Data/nuevo.xlsx", index=False)

# Ejercicio de manipulación de datos

Ahora vamos a aplicar los conceptos aprendidos en este tema a un conjunto de datos real, tomados de UniversiData y en concreto de la Complutense

https://www.universidata.es/datasets/ucm-acceso

De la anterior dirección descargamos los fichero de `UCM-Acceso-2024-25-Anonimizado`, tanto el csv como el excel.