# Ejercicio de manipulación de datos

## Importar los datos desde un fichero


***Leer un archivo CSV***

Un archivo CSV es un texto donde las columnas están separadas por comas.

In [40]:
import pandas as pd

df = pd.read_csv("./Data/ucm-acceso-2024-25-anonimizado.csv")
# número de filas y columnas
print(df.shape)

(14019, 78)

/var/folders/gz/w9zmh03s61l021wmll3psm_c0000gn/T/ipykernel_3352/2344200663.py:3: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("./Data/ucm-acceso-2024-25-anonimizado.csv")

***Leer un archivo Excel***

In [43]:
import openpyxl
df_excel = pd.read_excel("./Data/ucm-acceso-2024-25-anonimizado.xlsx")
# número de filas y columnas
print(df.shape)

(14019, 78)

## Explorar filas y columnas

Una tabla puede tener un gran número de entradas o filas, es por ello que se recomienda explorar una parte del dataframe con `head` y `tail`.

In [26]:
df.head()  # Primeras filas

,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
0,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,2,Familia numerosa general,3.0,Estudios Primarios,1.0,Directores y gerentes,4.0,Estudios Secundarios,2.0,Técnicos y profesionales científicos e intelec...
1,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,1,No,3.0,Estudios Primarios,1.0,Directores y gerentes,4.0,Estudios Secundarios,2.0,Técnicos y profesionales científicos e intelec...
2,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,1,No,3.0,Estudios Primarios,1.0,Directores y gerentes,3.0,Estudios Primarios,1.0,Directores y gerentes
3,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,2,Familia numerosa general,3.0,Estudios Primarios,1.0,Directores y gerentes,3.0,Estudios Primarios,1.0,Directores y gerentes
4,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,2,Familia numerosa general,3.0,Estudios Primarios,1.0,Directores y gerentes,3.0,Estudios Primarios,1.0,Directores y gerentes

In [28]:
df.tail()  # Últimas filas

,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
14014,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,2.0,Sin Estudios,12.0,Amos de casa,5.0,Estudios Superiores,NaN,NaN
14015,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,...",5.0,Estudios Superiores,11.0,Jubilado
14016,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,5.0,Estudios Superiores,11.0,Jubilado,2.0,Sin Estudios,3.0,Técnicos y profesionales de apoyo
14017,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,...",4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,..."
14018,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,4.0,Estudios Secundarios,NaN,NaN,4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,..."

In [44]:
print(df.columns)

Index(['IMPORTANTE', 'cod_universidad', 'des_universidad', 'curso_academico',
       'cod_campus', 'des_campus', 'cod_centro', 'des_centro',
       'cod_naturaleza_centro', 'des_naturaleza_centro', 'cod_tipo_estudio',
       'des_tipo_estudio', 'cod_titulacion', 'des_titulacion',
       'cod_comunidad_centro_sec', 'des_comunidad_centro_sec',
       'cod_provincia_centro_sec', 'des_provincia_centro_sec',
       'cod_municipio_centro_sec', 'des_municipio_centro_sec',
       'lat_municipio_centro_sec', 'lon_municipio_centro_sec',
       'cod_naturaleza_centro_sec', 'des_naturaleza_centro_sec',
       'nota_admision', 'cod_pais_fin_estudio_acceso',
       'des_pais_fin_estudio_acceso', 'lat_pais_fin_estudio_acceso',
       'lon_pais_fin_estudio_acceso', 'cod_continente_fin_estudio_acceso',
       'des_continente_fin_estudio_acceso',
       'cod_agregacion_paises_fin_estudio_acceso',
       'des_agregacion_paises_fin_estudio_acceso', 'cod_estudio_acceso',
       'des_estudio_acceso', 'cod_especialidad_acceso',
       'des_especialidad_acceso', 'des_tipo_especialidad_acceso',
       'cod_ocupacion_estudiante', 'des_ocupacion_estudiante',
       'anio_fin_estudio_acceso', 'cod_forma_admision', 'des_forma_admision',
       'ind_accede_al_SUE_por_1a_vez', 'anio_acceso_SUE',
       'ind_se_matricula_en_primero', 'ind_curso_adaptacion',
       'anio_nacimiento', 'cod_pais_nacionalidad', 'des_pais_nacionalidad',
       'lat_pais_nacionalidad', 'lon_pais_nacionalidad',
       'cod_continente_nacionalidad', 'des_continente_nacionalidad',
       'cod_agregacion_paises_nacionalidad',
       'des_agregacion_paises_nacionalidad', 'cod_pais_residencia',
       'des_pais_residencia', 'lat_pais_residencia', 'lon_pais_residencia',
       'cod_continente_residencia', 'des_continente_residencia',
       'cod_agregacion_paises_residencia', 'des_agregacion_paises_residencia',
       'cod_dedicacion', 'des_dedicacion', 'cod_genero', 'des_genero',
       'cod_familia_numerosa', 'des_familia_numerosa',
       'cod_nivel_estudios_madre', 'des_nivel_estudios_madre',
       'cod_ocupacion_madre', 'des_ocupacion_madre',
       'cod_nivel_estudios_padre', 'des_nivel_estudios_padre',
       'cod_ocupacion_padre', 'des_ocupacion_padre'],
      dtype='object')

Puede interesarnos una  varias columnas. Podemos seleccionar el número de columnas que queramos mediante los corchetes.

In [49]:
df[["des_titulacion","des_comunidad_centro_sec","nota_admision"]]

,des_titulacion,des_comunidad_centro_sec,nota_admision
0,GRADO EN DERECHO (2020) INSTITUTO SUPERIOR DE ...,Madrid,"7,586"
1,GRADO EN DERECHO (2020) INSTITUTO SUPERIOR DE ...,Galicia,"12,082"
2,GRADO EN DERECHO (2020) INSTITUTO SUPERIOR DE ...,Murcia,"6,317"
3,GRADO EN DERECHO (2020) INSTITUTO SUPERIOR DE ...,Madrid,"11,728"
4,GRADO EN DERECHO (2020) INSTITUTO SUPERIOR DE ...,Madrid,NaN
...,...,...,...
14014,GRADO EN CIENCIAS DE LAS RELIGIONES,Andalucía,"5,65"
14015,GRADO EN CIENCIAS DE LAS RELIGIONES,NaN,"7,63"
14016,GRADO EN CIENCIAS DE LAS RELIGIONES,NaN,5
14017,GRADO EN CIENCIAS DE LAS RELIGIONES,Madrid,"13,353"
14018,GRADO EN CIENCIAS DE LAS RELIGIONES,NaN,"6,5"

También podemos seleccionar unas filas concretas

In [51]:
df.iloc[0:2]

,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
0,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,2,Familia numerosa general,3.0,Estudios Primarios,1.0,Directores y gerentes,4.0,Estudios Secundarios,2.0,Técnicos y profesionales científicos e intelec...
1,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,1,No,3.0,Estudios Primarios,1.0,Directores y gerentes,4.0,Estudios Secundarios,2.0,Técnicos y profesionales científicos e intelec...

## Filtrar

Se **filtran** las filas u observaciones que cumplen una determinada restricción.

In [59]:
# df[df["nota_admision"] >= 10] da error de tipo
# Ese error suele aparecer porque la columna nota_admision está almacenada como texto (object o string) y no como números. 
# Debes convertir la columna a numérica, para ello usa
# pd.to_numeric() convierte la columna a un tipo numérico.
# errors="coerce" convierte los valores no válidos en NaN.

In [63]:
df["nota_admision"] = pd.to_numeric(df["nota_admision"], errors="coerce")

In [65]:
df[df["nota_admision"] >= 10]

,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
34,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,1,No,3.0,Estudios Primarios,1.0,Directores y gerentes,3.0,Estudios Primarios,1.0,Directores y gerentes
858,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027837.0,Facultad de Ciencias Químicas,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...,5.0,Estudios Superiores,5.0,"Trabajadores de los servicios de restauración,..."
862,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027837.0,Facultad de Ciencias Químicas,1,Público,...,1,No,5.0,Estudios Superiores,14.0,"Otra situación (Rentistas,…)",4.0,Estudios Secundarios,NaN,NaN
910,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,4.0,Estudios Secundarios,NaN,NaN,NaN,NaN,NaN,NaN
963,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,5.0,Estudios Superiores,5.0,"Trabajadores de los servicios de restauración,...",4.0,Estudios Secundarios,7.0,Artesanos y trabajadores cualificados de las i...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13642,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28043119.0,Facultad de Educación,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,4.0,Empleados de tipo contable y administrativo,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
13758,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027837.0,Facultad de Ciencias Químicas,1,Público,...,1,No,5.0,Estudios Superiores,3.0,Técnicos y profesionales de apoyo,4.0,Estudios Secundarios,8.0,Operadores de instalaciones y maquinaria y mon...
13781,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,2,Familia numerosa general,4.0,Estudios Secundarios,4.0,Empleados de tipo contable y administrativo,4.0,Estudios Secundarios,11.0,Jubilado
13846,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,5.0,Estudios Superiores,5.0,"Trabajadores de los servicios de restauración,...",5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
13993,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027758.0,Facultad de Ciencias Físicas,1,Público,...,2,Familia numerosa general,4.0,Estudios Secundarios,4.0,Empleados de tipo contable y administrativo,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...

In [71]:
df[(df["nota_admision"] >= 10) & (df["des_centro"] == "Facultad de Derecho")]

,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
910,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,4.0,Estudios Secundarios,NaN,NaN,NaN,NaN,NaN,NaN
963,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,5.0,Estudios Superiores,5.0,"Trabajadores de los servicios de restauración,...",4.0,Estudios Secundarios,7.0,Artesanos y trabajadores cualificados de las i...
1008,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...,4.0,Estudios Secundarios,1.0,Directores y gerentes
1038,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,5.0,Estudios Superiores,4.0,Empleados de tipo contable y administrativo,5.0,Estudios Superiores,11.0,Jubilado
10305,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,3.0,Estudios Primarios,5.0,"Trabajadores de los servicios de restauración,...",4.0,Estudios Secundarios,3.0,Técnicos y profesionales de apoyo
10919,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...,5.0,Estudios Superiores,1.0,Directores y gerentes
13846,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,5.0,Estudios Superiores,5.0,"Trabajadores de los servicios de restauración,...",5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...

## Ordenar

Se pueden **ordenar** los datos por determinadas columnas.

In [77]:
df.sort_values("nota_admision")

,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
14016,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,5.0,Estudios Superiores,11.0,Jubilado,2.0,Sin Estudios,3.0,Técnicos y profesionales de apoyo
4680,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027710.0,Facultad de Filología,1,Público,...,1,No,5.0,Estudios Superiores,NaN,NaN,NaN,NaN,NaN,NaN
5179,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027035.0,Facultad de Medicina,1,Público,...,2,Familia numerosa general,3.0,Estudios Primarios,5.0,"Trabajadores de los servicios de restauración,...",5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
1555,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027746.0,Facultad de Geografía e Historia,1,Público,...,1,No,5.0,Estudios Superiores,4.0,Empleados de tipo contable y administrativo,4.0,Estudios Secundarios,4.0,Empleados de tipo contable y administrativo
7752,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027710.0,Facultad de Filología,1,Público,...,1,No,4.0,Estudios Secundarios,12.0,Amos de casa,3.0,Estudios Primarios,7.0,Artesanos y trabajadores cualificados de las i...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14013,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,NaN,NaN,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,3.0,Técnicos y profesionales de apoyo,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
14014,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,2.0,Sin Estudios,12.0,Amos de casa,5.0,Estudios Superiores,NaN,NaN
14015,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,...",5.0,Estudios Superiores,11.0,Jubilado
14017,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,...",4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,..."
14018,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,4.0,Estudios Secundarios,NaN,NaN,4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,..."

In [75]:
df.sort_values("des_centro", ascending=False)

,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
752,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1012,"Campus del centro ""Centro de Enseñanza Superio...",28051219.0,Instituto de Estudios Bursátiles,2,Privado,...,1,No,5.0,Estudios Superiores,4.0,Empleados de tipo contable y administrativo,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
795,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1012,"Campus del centro ""Centro de Enseñanza Superio...",28051219.0,Instituto de Estudios Bursátiles,2,Privado,...,1,No,5.0,Estudios Superiores,13.0,Incapacitados para trabajar,4.0,Estudios Secundarios,1.0,Directores y gerentes
751,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1012,"Campus del centro ""Centro de Enseñanza Superio...",28051219.0,Instituto de Estudios Bursátiles,2,Privado,...,1,No,5.0,Estudios Superiores,10.0,Parado,5.0,Estudios Superiores,1.0,Directores y gerentes
753,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1012,"Campus del centro ""Centro de Enseñanza Superio...",28051219.0,Instituto de Estudios Bursátiles,2,Privado,...,3,Familia numerosa especial,5.0,Estudios Superiores,4.0,Empleados de tipo contable y administrativo,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
754,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1012,"Campus del centro ""Centro de Enseñanza Superio...",28051219.0,Instituto de Estudios Bursátiles,2,Privado,...,1,No,5.0,Estudios Superiores,12.0,Amos de casa,5.0,Estudios Superiores,4.0,Empleados de tipo contable y administrativo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14009,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,NaN,NaN,1,Público,...,1,No,5.0,Estudios Superiores,3.0,Técnicos y profesionales de apoyo,4.0,Estudios Secundarios,1.0,Directores y gerentes
14010,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,NaN,NaN,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,1.0,Directores y gerentes,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
14011,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,NaN,NaN,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
14012,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,NaN,NaN,1,Público,...,1,No,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
14013,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,NaN,NaN,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,3.0,Técnicos y profesionales de apoyo,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...

## Crear nuevas columnas

Podemos crear nuevas columnas resultado de realizar cálculos.

In [226]:
df["des_centro"] = df["Edad"]>=18
df

     Nombre  Edad    Ciudad  Menor_edad
0     Sonia    24    Madrid        True
1    Carmen    31   Sevilla        True
2     Marta    28  Valencia        True
3      Jose    40   Segovia        True
4    Nieves    16    Madrid       False
5  Carlitos    12    Madrid       False

## Eliminar columnas

In [228]:
df = df.drop(columns = "Menor_edad")
df

     Nombre  Edad    Ciudad
0     Sonia    24    Madrid
1    Carmen    31   Sevilla
2     Marta    28  Valencia
3      Jose    40   Segovia
4    Nieves    16    Madrid
5  Carlitos    12    Madrid

## Renombrar columnas

In [230]:
df = df.rename(columns = {"Ciudad":"Población"})
df

     Nombre  Edad Población
0     Sonia    24    Madrid
1    Carmen    31   Sevilla
2     Marta    28  Valencia
3      Jose    40   Segovia
4    Nieves    16    Madrid
5  Carlitos    12    Madrid

## Añadir una fila con un valor nulo

Para añadir una fila, decimos que pasada la última fila (len(df)) se edita df.loc[ ] y se le asigna una lista de datos. En este caso, voy a aprovechar que añado una fila para dejar una celda sin dato. Por ejemplo, dejamos la edad sin conocer.

Aviso: cada vez que ejecutes esta intrucción, se añade una fila nueva.

In [232]:
df.loc[len(df)] = ["Amelia", None, "Toledo"]

## Valores nulos

In [234]:
df.isnull()

   Nombre   Edad  Población
0   False  False      False
1   False  False      False
2   False  False      False
3   False  False      False
4   False  False      False
5   False  False      False
6   False   True      False

## Eliminar filas con datos vacíos:

En ocasiones, no nos interesan las filas que no son completas. En estos casos se eliminan dichas filas.

In [237]:
df.dropna()

     Nombre Edad Población
0     Sonia   24    Madrid
1    Carmen   31   Sevilla
2     Marta   28  Valencia
3      Jose   40   Segovia
4    Nieves   16    Madrid
5  Carlitos   12    Madrid

## Operaciones sobre una columna numérica

A continuación ponemos una muestra, para más detalle se puede consultar la documentación de Python (https://docs.python.org/es/3.14/builtins/functions.html).

In [239]:
df["Edad"].mean()

25.166666666666668

In [240]:
df["Edad"].max()

40

In [241]:
df["Edad"].min()

12

In [242]:
df["Edad"].sum()

151

## Guardar datos

In [37]:
# Guardar como CSV:

df.to_csv("./Data/nuevo.csv", index=False)

# Guardar como Excel:

df.to_excel("./Data/nuevo.xlsx", index=False)